import { useState, type HTMLAttributes, type ImgHTMLAttributes } from 'react';
import { useTilt } from '../lib/useTilt';
import type { Project, ProjectImage } from '../content/projects';

type ImageProps = ImgHTMLAttributes<HTMLImageElement> & {
  src: string;
  alt: string;
  width: number;
  height: number;
  priority?: boolean;
};

function Image({ priority, loading, decoding, src, sizes, ...props }: ImageProps) {
  // Serve the much smaller WebP (generated by scripts/optimize-images.mjs)
  // with the original PNG/JPEG as a fallback for browsers without WebP support.
  // The -640w variant exists for every source (the script generates it
  // unconditionally), so small display slots never download the full-size file.
  const webpSrc = src.replace(/\.(png|jpe?g)$/i, '.webp');
  const webp640Src = src.replace(/\.(png|jpe?g)$/i, '-640w.webp');
  return (
    <picture className="contents">
      <source srcSet={`${webp640Src} 640w, ${webpSrc} 1200w`} sizes={sizes} type="image/webp" />
      <img
        src={src}
        loading={priority ? 'eager' : loading ?? 'lazy'}
        decoding={priority ? 'sync' : decoding ?? 'async'}
        {...props}
      />
    </picture>
  );
}

function imageFitClass(image: ProjectImage) {
  return image.fit === 'cover' ? 'object-cover' : 'object-contain';
}

// Project card with a subtle pointer-follow 3D tilt on desktop; on touch
// devices the hook is inert and the CSS hover lift still applies.
function TiltArticle(props: HTMLAttributes<HTMLElement>) {
  const ref = useTilt<HTMLElement>(4);
  return <article ref={ref} {...props} />;
}

function ScreenshotGallery({
  project,
  priority = false,
  onOpenDetails,
  maxThumbnails,
  featured = false,
}: {
  project: Project;
  priority?: boolean;
  onOpenDetails?: () => void;
  maxThumbnails?: number;
  featured?: boolean;
}) {
  const [hero, ...thumbnails] = project.images;
  const visibleThumbnails = typeof maxThumbnails === 'number' ? thumbnails.slice(0, maxThumbnails) : thumbnails;
  const lightFrame = project.lightFrame ?? project.slug === 'alhambra-guide-platform';
  const frameBackground = lightFrame ? 'bg-[#FAF7F2]' : 'bg-[#0F2A44]';
  const thumbnailBackground = lightFrame ? 'bg-white' : 'bg-[#122F4B]';

  return (
    <div className={frameBackground}>
      <button
        type="button"
        onClick={onOpenDetails}
        className={`block w-full overflow-hidden rounded-t-2xl p-2 text-left ${frameBackground} ${
          featured ? 'aspect-[16/10] sm:aspect-[16/8]' : 'aspect-[16/11] sm:aspect-[16/10]'
        }`}
        aria-label={`Open details for ${project.title}`}
      >
        <Image
          src={hero.src}
          alt={hero.alt}
          width={1200}
          height={720}
          priority={priority}
          sizes="(min-width: 768px) 50vw, 100vw"
          className={`h-full w-full rounded-xl ${imageFitClass(hero)} transition-all duration-300 hover:opacity-95`}
          style={{ objectPosition: hero.position ?? 'center top' }}
        />
      </button>

      <div className="grid grid-cols-2 gap-2 p-2 pt-0">
        {visibleThumbnails.map((image) => (
          <button
            key={image.src}
            type="button"
            onClick={onOpenDetails}
            className={`aspect-[4/3] overflow-hidden rounded-lg p-1.5 text-left ${thumbnailBackground}`}
            aria-label={`Open details for ${project.title}`}
          >
            <Image
              src={image.src}
              alt={image.alt}
              width={600}
              height={450}
              sizes="(min-width: 768px) 25vw, 50vw"
              className={`h-full w-full rounded-md ${imageFitClass(image)} transition-all duration-200 hover:opacity-90`}
              style={{ objectPosition: image.position ?? 'center top' }}
            />
          </button>
        ))}
      </div>
    </div>
  );
}

/** The project card grid plus the details modal, shared by the homepage
 *  Recent Work section and the full /work page. The first card renders
 *  full-width as the lead. */
export default function ProjectShowcase({ projects }: { projects: Project[] }) {
  const [selectedProject, setSelectedProject] = useState<Project | null>(null);

  return (
    <>
      <div className="mt-12 grid grid-cols-1 gap-8 md:grid-cols-2">
        {projects.map((project, projectIndex) => (
          <TiltArticle
            key={project.slug}
            className={`group flex flex-col overflow-hidden rounded-2xl bg-white shadow-sm transition-all duration-300 ease-out hover:-translate-y-1 hover:shadow-md ${
              projectIndex === 0 ? 'md:col-span-2' : ''
            }`}
            style={{ border: '1px solid #E2DDD6' }}
          >
            <ScreenshotGallery
              project={project}
              onOpenDetails={() => setSelectedProject(project)}
              maxThumbnails={2}
              featured={projectIndex === 0}
            />

            <div className={`flex flex-1 flex-col p-6 ${projectIndex === 0 ? 'md:p-8' : 'md:p-7'}`}>
              <div className="flex flex-wrap gap-2">
                {project.tags.map((tag) => (
                  <span
                    key={tag}
                    className="inline-flex items-center rounded-full px-3 py-1"
                    style={{
                      background: 'rgba(229, 116, 43, 0.10)',
                      color: '#C76024',
                      fontFamily: "'Inter', system-ui, -apple-system, 'Segoe UI', Arial, sans-serif",
                      fontSize: '0.8125rem',
                      fontWeight: 500,
                      letterSpacing: '0',
                      lineHeight: 1.35,
                      boxShadow: 'inset 0 0 0 1px rgba(229, 116, 43, 0.14)',
                    }}
                  >
                    {tag}
                  </span>
                ))}
              </div>

              <h3
                className="mt-5"
                style={{
                  fontFamily: "'Inter', system-ui, -apple-system, 'Segoe UI', Arial, sans-serif",
                  fontWeight: 700,
                  fontSize:
                    projectIndex === 0 ? 'clamp(1.85rem, 3vw, 2.25rem)' : 'clamp(1.45rem, 2vw, 1.75rem)',
                  color: '#0F2A44',
                  letterSpacing: '-0.02em',
                  lineHeight: 1.16,
                }}
              >
                {project.title}
              </h3>

              <p
                className="mt-3"
                style={{
                  fontFamily: "'Inter', system-ui, -apple-system, 'Segoe UI', Arial, sans-serif",
                  fontSize: '1rem',
                  color: '#425061',
                  lineHeight: 1.72,
                  display: '-webkit-box',
                  WebkitLineClamp: 2,
                  WebkitBoxOrient: 'vertical',
                  overflow: 'hidden',
                }}
              >
                {project.description}
              </p>

              <p
                className="mt-auto pt-6"
                style={{
                  fontFamily: "'Inter', system-ui, -apple-system, 'Segoe UI', Arial, sans-serif",
                  fontSize: '0.875rem',
                  color: '#5F6F80',
                  lineHeight: 1.6,
                }}
              >
                {project.techStack}
              </p>

              <div className="mt-5 flex flex-wrap items-center gap-3">
                {project.liveUrl && (
                  <a
                    href={project.liveUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex min-h-10 items-center rounded-lg px-4 py-2 text-sm font-medium text-white transition-all duration-200 hover:-translate-y-px"
                    style={{
                      background: '#E5742B',
                      fontFamily: "'Inter', system-ui, -apple-system, 'Segoe UI', Arial, sans-serif",
                    }}
                  >
                    View Project
                  </a>
                )}

                {project.isPrivate && (
                  <span
                    className="inline-flex min-h-10 items-center rounded-lg px-4 py-2 text-sm font-medium"
                    style={{
                      background: '#FAF7F2',
                      color: '#544D44',
                      fontFamily: "'Inter', system-ui, -apple-system, 'Segoe UI', Arial, sans-serif",
                    }}
                  >
                    Private Project
                  </span>
                )}

                <button
                  type="button"
                  onClick={() => setSelectedProject(project)}
                  className="inline-flex min-h-10 items-center rounded-lg border px-4 py-2 text-sm font-medium transition-all duration-200 hover:-translate-y-px hover:text-[#E5742B]"
                  style={{
                    borderColor: '#E2DDD6',
                    color: '#0F2A44',
                    fontFamily: "'Inter', system-ui, -apple-system, 'Segoe UI', Arial, sans-serif",
                  }}
                >
                  See Details
                </button>
              </div>
            </div>
          </TiltArticle>
        ))}
      </div>

      {selectedProject && (
        <div
          className="fixed inset-0 z-[60] flex items-center justify-center bg-[#0F2A44]/70 px-4 py-8"
          role="dialog"
          aria-modal="true"
          aria-labelledby="project-detail-title"
          onClick={() => setSelectedProject(null)}
        >
          <div
            className="max-h-[90vh] w-full max-w-5xl overflow-y-auto rounded-2xl bg-white shadow-2xl"
            style={{ border: '1px solid #E2DDD6' }}
            onClick={(event) => event.stopPropagation()}
          >
            <div className="flex items-start justify-between gap-6 border-b p-6" style={{ borderColor: '#E2DDD6' }}>
              <div>
                <p
                  style={{
                    fontFamily: "'Inter', system-ui, -apple-system, 'Segoe UI', Arial, sans-serif",
                    fontSize: '0.75rem',
                    fontWeight: 600,
                    letterSpacing: '0.04em',
                    color: '#C76024',
                  }}
                >
                  Project Details
                </p>
                <h3
                  id="project-detail-title"
                  className="mt-2"
                  style={{
                    fontFamily: "'Newsreader', Georgia, 'Times New Roman', serif",
                    fontWeight: 600,
                    fontSize: 'clamp(1.75rem, 4vw, 2.35rem)',
                    color: '#0F2A44',
                    letterSpacing: '-0.005em',
                    lineHeight: 1.1,
                  }}
                >
                  {selectedProject.fullTitle ?? selectedProject.title}
                </h3>
              </div>

              <button
                type="button"
                onClick={() => setSelectedProject(null)}
                className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full text-2xl leading-none transition-colors hover:bg-[#FAF7F2]"
                aria-label="Close project details"
                style={{ color: '#0F2A44' }}
              >
                ×
              </button>
            </div>

            <div className="grid gap-6 p-6 lg:grid-cols-[1.35fr_0.65fr]">
              <div>
                <ScreenshotGallery project={selectedProject} />
              </div>

              <div className="space-y-6">
                {selectedProject.details.summary && (
                  <div>
                    <h4
                      style={{
                        fontFamily: "'Inter', system-ui, -apple-system, 'Segoe UI', Arial, sans-serif",
                        fontWeight: 600,
                        color: '#0F2A44',
                      }}
                    >
                      Summary
                    </h4>
                    <p
                      className="mt-2"
                      style={{
                        fontFamily: "'Inter', system-ui, -apple-system, 'Segoe UI', Arial, sans-serif",
                        fontSize: '0.9375rem',
                        color: '#2A2A2A',
                        lineHeight: 1.65,
                      }}
                    >
                      {selectedProject.details.summary}
                    </p>
                  </div>
                )}

                <div>
                  <h4
                    style={{
                      fontFamily: "'Inter', system-ui, -apple-system, 'Segoe UI', Arial, sans-serif",
                      fontWeight: 600,
                      color: '#0F2A44',
                    }}
                  >
                    What I built
                  </h4>
                  {Array.isArray(selectedProject.details.built) ? (
                    <ul
                      className="mt-2 space-y-1.5"
                      style={{
                        fontFamily: "'Inter', system-ui, -apple-system, 'Segoe UI', Arial, sans-serif",
                        fontSize: '0.9375rem',
                        color: '#2A2A2A',
                        lineHeight: 1.55,
                      }}
                    >
                      {selectedProject.details.built.map((item) => (
                        <li key={item}>• {item}</li>
                      ))}
                    </ul>
                  ) : (
                    <p
                      className="mt-2"
                      style={{
                        fontFamily: "'Inter', system-ui, -apple-system, 'Segoe UI', Arial, sans-serif",
                        fontSize: '0.9375rem',
                        color: '#2A2A2A',
                        lineHeight: 1.65,
                      }}
                    >
                      {selectedProject.details.built}
                    </p>
                  )}
                </div>

                <div>
                  <h4
                    style={{
                      fontFamily: "'Inter', system-ui, -apple-system, 'Segoe UI', Arial, sans-serif",
                      fontWeight: 600,
                      color: '#0F2A44',
                    }}
                  >
                    Business impact
                  </h4>
                  {Array.isArray(selectedProject.details.value) ? (
                    <ul
                      className="mt-2 space-y-1.5"
                      style={{
                        fontFamily: "'Inter', system-ui, -apple-system, 'Segoe UI', Arial, sans-serif",
                        fontSize: '0.9375rem',
                        color: '#2A2A2A',
                        lineHeight: 1.55,
                      }}
                    >
                      {selectedProject.details.value.map((item) => (
                        <li key={item}>• {item}</li>
                      ))}
                    </ul>
                  ) : (
                    <p
                      className="mt-2"
                      style={{
                        fontFamily: "'Inter', system-ui, -apple-system, 'Segoe UI', Arial, sans-serif",
                        fontSize: '0.9375rem',
                        color: '#2A2A2A',
                        lineHeight: 1.65,
                      }}
                    >
                      {selectedProject.details.value}
                    </p>
                  )}
                </div>

                <div>
                  <h4
                    style={{
                      fontFamily: "'Inter', system-ui, -apple-system, 'Segoe UI', Arial, sans-serif",
                      fontWeight: 600,
                      color: '#0F2A44',
                    }}
                  >
                    Tools used
                  </h4>
                  <p
                    className="mt-2"
                    style={{
                      fontFamily: "'Inter', system-ui, -apple-system, 'Segoe UI', Arial, sans-serif",
                      fontSize: '0.875rem',
                      color: '#5F6F80',
                      lineHeight: 1.6,
                    }}
                  >
                    {selectedProject.techStack}
                  </p>
                </div>

                {selectedProject.liveUrl && (
                  <a
                    href={selectedProject.liveUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex min-h-10 items-center rounded-lg px-4 py-2 text-sm font-medium text-white transition-all duration-200 hover:-translate-y-px"
                    style={{
                      background: '#E5742B',
                      fontFamily: "'Inter', system-ui, -apple-system, 'Segoe UI', Arial, sans-serif",
                    }}
                  >
                    View Project
                  </a>
                )}

                {selectedProject.details.privacy && (
                  <p
                    style={{
                      fontFamily: "'Inter', system-ui, -apple-system, 'Segoe UI', Arial, sans-serif",
                      fontSize: '0.8125rem',
                      color: '#544D44',
                      lineHeight: 1.6,
                    }}
                  >
                    {selectedProject.details.privacy}
                  </p>
                )}
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
